//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace peresvet.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudniki
    {
        public int sotrudnik_id { get; set; }
        public string Familiya { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public Nullable<int> Vozrast { get; set; }
        public Nullable<int> Stazh { get; set; }
        public int Status_id { get; set; }
        public int Dolzhnost_id { get; set; }
    
        public virtual Dolzhnost Dolzhnost { get; set; }
        public virtual Status Status { get; set; }
    }
}
